version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27018:27017"
    environment:
      - "DATABASE_URL = ${DATABASE_URL}"