version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    formatter: default  
    class: logging.FileHandler
    filename: log_file.log  
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
root:
  level: DEBUG
  handlers:
    - default
    - file 
  propagate: no
